package com.github.eirslett.maven.plugins.frontend.lib;

import com.diffblue.deeptestutils.Reflector;
import com.github.eirslett.maven.plugins.frontend.lib.ProxyConfig;
import org.junit.Assert;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;

import java.lang.reflect.Array;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.ArrayList;

public class DefaultYarnRunnerTestCase {

  @Rule public ExpectedException thrown = ExpectedException.none();

  /* testedClasses: YarnRunner */
  /*
   * Test generated by Diffblue Deeptest.
   * This test case covers:
   *  - conditional line 23 branch to line 23
   *  - conditional line 23 branch to line 27
   *  - conditional line 27 branch to line 45
   */

  @Test
  public void buildArgumentsInputNotNullNotNullOutput0()
      throws NoSuchMethodException, IllegalAccessException, InvocationTargetException {

    // Arrange
    ProxyConfig proxyConfig = ((ProxyConfig)Reflector.getInstance(
        "com.github.eirslett.maven.plugins.frontend.lib.ProxyConfig"));
    ArrayList arrayList = new ArrayList();
    Reflector.setField(proxyConfig, "proxies", arrayList);
    String npmRegistryURL = "";

    // Act
    Class<?> c =
        Reflector.forName("com.github.eirslett.maven.plugins.frontend.lib.DefaultYarnRunner");
    Method m = c.getDeclaredMethod(
        "buildArguments",
        Reflector.forName("com.github.eirslett.maven.plugins.frontend.lib.ProxyConfig"),
        Reflector.forName("java.lang.String"));
    m.setAccessible(true);
    java.util.List<String> retval =
        (java.util.List<String>)m.invoke(null, proxyConfig, npmRegistryURL);

    // Assert result
    ArrayList<String> arrayList1 = new ArrayList<String>();
    Assert.assertEquals(arrayList1, retval);
  }

  /* testedClasses: YarnRunner */
  /*
   * Test generated by Diffblue Deeptest.
   * This test case covers:
   *  - conditional line 23 branch to line 23
   *  - conditional line 23 branch to line 24
   *  - conditional line 24 branch to line 24
   *  - conditional line 27 branch to line 45
   */

  @Test
  public void buildArgumentsInputNotNullNotNullOutput1()
      throws NoSuchMethodException, IllegalAccessException, InvocationTargetException {

    // Arrange
    ProxyConfig proxyConfig = ((ProxyConfig)Reflector.getInstance(
        "com.github.eirslett.maven.plugins.frontend.lib.ProxyConfig"));
    ArrayList arrayList = new ArrayList();
    Reflector.setField(proxyConfig, "proxies", arrayList);
    String npmRegistryURL = "BB";

    // Act
    Class<?> c =
        Reflector.forName("com.github.eirslett.maven.plugins.frontend.lib.DefaultYarnRunner");
    Method m = c.getDeclaredMethod(
        "buildArguments",
        Reflector.forName("com.github.eirslett.maven.plugins.frontend.lib.ProxyConfig"),
        Reflector.forName("java.lang.String"));
    m.setAccessible(true);
    java.util.List<String> retval =
        (java.util.List<String>)m.invoke(null, proxyConfig, npmRegistryURL);

    // Assert result
    ArrayList<String> arrayList1 = new ArrayList<String>();
    arrayList1.add("--registry=BB");
    Assert.assertEquals(arrayList1, retval);
  }
}
