'use strict';

console.log(`ENVIRONMENT_VARIABLE_FILE_1: ${process.env.ENVIRONMENT_VARIABLE_FILE_1}`)
console.log(`ENVIRONMENT_VARIABLE_OVERRIDE: ${process.env.ENVIRONMENT_VARIABLE_OVERRIDE}`)
console.log(`ENVIRONMENT_VARIABLE_4: ${process.env.ENVIRONMENT_VARIABLE_4}`)
