name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java (required for Maven)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Step 3: Build the project
      - name: Build with Maven
        run: mvn clean install

      # Step 4: Run source code scan with Semgrep
      - name: Run Semgrep
        run: |
          pip install semgrep
          semgrep scan --config=auto --json > semgrep-results.json

      # Step 5: Upload scan report as an artifact
      - name: Upload Semgrep report
        uses: actions/upload-artifact@v3
        with:
          name: semgrep-report
          path: semgrep-results.json

